apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: podinfo
  annotations:
    zarf.dev/connect-description: "Open PodInfo in a browser"
  labels:
    zarf.dev/connect-name: podinfo
spec:
  type: ClusterIP
  selector:
    app: podinfo
  ports:
    - name: http
      port: 9898
      protocol: TCP
      targetPort: 9898
    - name: grpc
      port: 9999
      protocol: TCP
      targetPort: 9999
